CREATE OR REPLACE DIRECTORY ext_file_ds AS 'C:\Users\razva\Documents\football_source';
GRANT READ, WRITE ON DIRECTORY ext_file_ds TO FDBO;

DROP TABLE TEAM_ALIASES;

CREATE TABLE TEAM_ALIASES (
  source_name      VARCHAR2(100),
  canonical_name   VARCHAR2(100)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY ext_file_ds
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE SKIP 1
    FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('team_aliases.csv')
)
REJECT LIMIT UNLIMITED;

SELECT * FROM TEAM_ALIASES;
